# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186iUhZ8qk3KAlweyzyWZqG8C8LRiRr8T

#1. INSTALL DEPENDANCIES
"""

import streamlit as st
import boto3
import os
from langchain_aws import ChatBedrock
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

"""#2. PAGE CONFIGURATION"""

st.set_page_config(page_title=" Legacy Code Summarizer", layout="wide")

"""#3. GET CREDENTIALS"""

try:
    aws_access_key = st.secrets["AWS_ACCESS_KEY_ID"]
    aws_secret_key = st.secrets["AWS_SECRET_ACCESS_KEY"]
    aws_region = st.secrets.get("AWS_DEFAULT_REGION", "eu-central-1")
except Exception as e:
    st.error("Missing Secrets! Please add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to Streamlit settings.")
    st.stop()

"""#4. BEDROCK LOGIC"""

def get_llm():
    client = boto3.client(
        service_name="bedrock-runtime",
        region_name=aws_region,
        aws_access_key_id=aws_access_key,
        aws_secret_access_key=aws_secret_key
    )

    # Using your specific EU Inference Profile/Model ID
    return ChatBedrock(
        client=client,
        model_id="eu.anthropic.claude-3-5-sonnet-20240620-v1:0",
        model_kwargs={"temperature": 0.0, "max_tokens": 4000}
    )

def analyze_code(code, lang):
    llm = get_llm()
    prompt = ChatPromptTemplate.from_template("Explain this {lang} code logic: {code}")
    chain = prompt | llm | StrOutputParser()
    return chain.invoke({"lang": lang, "code": code})

"""#4. USER INTERFACE"""

st.title(" AI Legacy Code Summarizer")
st.markdown(f"**Region:** `{aws_region}` | **Model:** `Sonnet 3.5 EU`")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Input")
    lang = st.selectbox("Source Language", ["Python", "Java", "COBOL", "C++"])
    code = st.text_area("Paste your legacy code here", height=400)
    btn = st.button("Generate Summary", type="primary")

with col2:
    st.subheader("Analysis")
    if btn and code:
        with st.spinner("Analyzing code architecture..."):
            try:
                res = analyze_code(code, lang)
                st.success("Analysis Complete")
                st.markdown(res)
            except Exception as e:
                st.error(f"Bedrock Error: {e}")
    elif btn and not code:
        st.warning("Please paste some code first!")